### ISSUE TITLE
InitialCameraUpdate

### ISSUE THREAD

**Issue by mammadkoma** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#11]
I can set InitialCameraUpdate="35.11, 54, 4.5, 0, 0" in xaml.
How can I do this by binding in ViewModel?

**Comment by mammadkoma** [comment]
No one ?!

**Comment by nuitsjp** [comment]
I'm sorry for the late reply.
The method is under consideration now.
I'd like to reply soon.

**Comment by mammadkoma** [comment]
Thanks you
another thing is important is call MoveToRegion() method from view model.

**Comment by nuitsjp** [comment]
In Release 2.2.0, CameraPosition can be bound.
However, Map specification does not seem to be able to move the camera before display.

If you want to move the camera, move it with an Appering event etc.
Sample:
https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/blob/master/Sample/GoogleMaps.Bindings/GoogleMaps.Bindings/Views/UpdateCameraPositionPage.xaml

Region is possible.
Sample:
https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/blob/master/Sample/GoogleMaps.Bindings/GoogleMaps.Bindings/Views/UpdateRegionPage.xaml
