### ISSUE TITLE
Pin Binding not working

### ISSUE THREAD

**Issue by tomh4** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#12]
Hello,

The binding on the Pins somehow doesn´t work.
I am getting this message in the output : 
`Binding: 'Pins' property not found on 'Controls.MapView', target property: 'Xamarin.Forms.GoogleMaps.Bindings.BindingPinsBehavior.Value'`
However, all other bindings on the same XAML do work.

Any suggestions ?

XAML Snippet : 
```
...
            <custom:MapView x:Name="MapLayer"  Grid.Row="0" Grid.Column="0" Grid.RowSpan="5">
                <custom:MapView.Behaviors>
                    <bindings:BindingPinsBehavior Value="{Binding Pins}"/>
                </custom:MapView.Behaviors>
            </custom:MapView>
...
```

Whereas MapView is a class that inherits form Xamarin.Forms.GoogleMaps.Map

**Comment by nuitsjp** [comment]
It seems that the Pins property of custom:MapView can be accessed.
Does custom:MapView inherit from Xamarin.Forms.GoogleMaps.Map?
If you need further advice, please present a reproducible minimum project with Github etc.

**Comment by tomh4** [comment]
There you go :
[Reproduction Project](https://github.com/tomh4/Xamarin.Forms.GoogleMaps.Bindings-Repro)

It does not find the Binding "Pins"

**Comment by nuitsjp** [comment]
Can not build sample code.
There is no namespace in MapView.
I have not had time today, so I will take a look at it tomorrow.

**Comment by nuitsjp** [comment]
Apparently, it seems that it is not working properly in the subclass of Map. Details will be analyzed again.

**Comment by tomh4** [comment]
Great keep me updated!

**Comment by stefancvetkovic** [comment]
This is also problem with my code. Bindning Pins doesnt work.

**Comment by nuitsjp** [comment]
This problem was caused by the user side.
I sent a Pull Request.
please confirm.
https://github.com/tomh4/Xamarin.Forms.GoogleMaps.Bindings-Repro/pull/1
