### ISSUE TITLE
Value property marked as private set

### ISSUE THREAD

**Issue by seanyda** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#14]
Hi,

I write my UI in C# and I'm having some issues using the BindingPinsBehaviour. It has two properties available, BindingContext and Value. 

Value seems to be a private set; but I can see you're setting it successfully in your XAML example. 

```CSHARP
new Map {
         Behaviors = {
                new BindingPinsBehavior {
                         Value = new Binding("Pins")
                 }
        },
}.Row(1).Bind(IsVisibleProperty, "MapViewVisible")
```

I'm being told Value is readonly--.

Thanks,
Sean

**Comment by nuitsjp** [comment]
First of all I want you to know.
My English ability is very poor.
So, I may not understand what you want to convey.


Well, Pins property of Map does not have set.
https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Map.cs#L195

Therefore, there is no point in disclosing the set of BindingPinsBehavior.
So set is private.

Close once.
If I understand mistakes, please tell me your purpose once again.
