### ISSUE TITLE
OnAppearing set pins

### ISSUE THREAD

**Issue by stefancvetkovic** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#16]
IS there any event for maps OnAppering (from XAML)  to set initial pins?

**Comment by nuitsjp** [comment]
Unfortunately not.
It is recommended to use it with Xamarin.Forms.BehaviorsPack.
The following article will be helpful.
https://blog.nuits.jp/ultimately-simplifying-command-binding-to-all-events-xamarin-forms-behaviorspack-2-0-0-released-66be82e9f0dc
