### ISSUE TITLE
The property 'Request' was not found in type 'MoveCameraBehavior'

### ISSUE THREAD

**Issue by GianlucaMancusi** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#18]
I'm trying to understand why I'm getting this error.

> The property 'Request' was not found in type 'MoveCameraBehavior'

This is my InAutoGuidaPage.xaml code:
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="GalileoQuiz.Views.InAutoGuidaPage"
             xmlns:googleMaps="clr-namespace:Xamarin.Forms.GoogleMaps;assembly=Xamarin.Forms.GoogleMaps"
             xmlns:bindings="clr-namespace:Xamarin.Forms.GoogleMaps.Bindings;assembly=Xamarin.Forms.GoogleMaps.Bindings"
             >
    <Grid>
        <googleMaps:Map InitialCameraUpdate="{Binding InitialCameraUpdate}" VerticalOptions="FillAndExpand">
            <googleMaps:Map.Behaviors>
                <bindings:BindingPolylinesBehavior Value="{Binding Polylines}"/>
                <bindings:MoveCameraBehavior Request="{Binding MoveCameraRequest}"/>
            </googleMaps:Map.Behaviors>
        </googleMaps:Map>
    </Grid>
</ContentPage>
```
I get this error even when I write another binding like this:
`
<bindings:UpdateCameraPositionBehavior CameraUpdate="{Binding CameraUpdate}" Duration="{Binding Duration}"/>
`
> The property 'CameraUpdate' was not found in type 'UpdateCameraPositionBehavior'

And others like these.

Any suggestions? What am I forgetting?
I'm using Prism Framework with MVVM.

**Comment by nuitsjp** [comment]
I can not judge with just this.
Can you publish the reproduction program to Github etc?

**Comment by GianlucaMancusi** [comment]
> I can not judge with just this.
> Can you publish the reproduction program to Github etc?

Sorry, I can't publish the project code.
I do not understand why your bindings code like this is not visible in my xaml:

```
public static readonly BindableProperty RequestProperty = BindableProperty.Create("Request", typeof(MoveCameraRequest), typeof(MoveCameraBehavior), null, propertyChanged: OnRequestChanged);
```

While code like this is seen from the xaml file:
```
private static readonly BindablePropertyKey ValuePropertyKey = BindableProperty.CreateReadOnly("Value", typeof(ObservableCollection<Polygon>), typeof(BindingPolygonsBehavior), default(ObservableCollection<Polygon>));

public static readonly BindableProperty ValueProperty = ValuePropertyKey.BindableProperty;
```

Can you think of something? Do you have any suggestions? I think it's probably a problem with my project.
If you need another piece of code, let me know. Thank you!

**Comment by nuitsjp** [comment]
I'm not requesting publication of production code.
Please provide a minimum source that can confirm the trouble recreation.
My sample code is working.

**Comment by GianlucaMancusi** [comment]
> Please provide a minimum source that can confirm the trouble recreation.

I can not figure out exactly how to reproduce the error.

> My sample code is working.

I tried to download and compile your GitHub sample project and it gives me the same errors, is it possible to be a version problem related to Xamarin.Forms or something else?
I am using Xamarin.Forms 3.3.0.967583.

**Comment by nuitsjp** [comment]
I will check if my sample works.
But I do not have time right now.
I can not promise that I can do any time.

**Comment by GianlucaMancusi** [comment]
Okay, thanks. In the meantime I'll keep investigating the problem. I wish you could tell me which version are you actually using.

**Comment by Sonnenspeer** [comment]
There is missing a public "Request" property to make the property publicly visible in XAML.

Something like:
```
public MoveCameraRequest Request 
{
    get { return GetValue(RequestProperty); }
    set { SetValue(RequestProperty, value); }
}
```

**Comment by guykeller** [comment]
Joining this question.
I get the same error, and also got the same error when I tried @Sonnenspeer solution.

Here is my view:
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:maps="clr-namespace:Xamarin.Forms.GoogleMaps;assembly=Xamarin.Forms.GoogleMaps"
             x:Class="DogHelpers.Views.MapPage"
             xmlns:bindings="clr-namespace:Xamarin.Forms.GoogleMaps.Bindings;assembly=Xamarin.Forms.GoogleMaps.Bindings"
             xmlns:ViewModels="clr-namespace:DogHelpers.ViewModels">
    <ContentPage.BindingContext>
        <ViewModels:MapPageViewModel/>
    </ContentPage.BindingContext>
    <ContentPage.Content>
        <StackLayout>
            <maps:Map VerticalOptions="FillAndExpand">
                <maps:Map.Behaviors>
                    <bindings:BindingVisibleRegionBehavior Value="{Binding VisibleRegion}"/>
                    <bindings:MoveCameraBehavior Request="{Binding MoveToRegionRequest}"/>
                </maps:Map.Behaviors>
            </maps:Map>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>`

And my ViewModel:
`using DogHelpers.Models;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using Xamarin.Forms.GoogleMaps;
using Xamarin.Forms.GoogleMaps.Bindings;

namespace DogHelpers.ViewModels
{
    public class MapPageViewModel : BindableObject
    {

        public Coordinates GetMostRecentDogLocation()
        {
            return new Coordinates
            {
                Latitude = 32.120853,
                Longitude = 34.840729
            };
        }

        private MapSpan _visibleRegion;
        public MapSpan VisibleRegion
        {
            get => _visibleRegion;
            set
            {
                _visibleRegion = value;
                OnPropertyChanged();
            }
        }

        public MoveToRegionRequest MoveToRegionRequest { get; } = new MoveToRegionRequest();

        public void Initialize(object navigationData)
        {
            Coordinates mostRecentDogLocation = GetMostRecentDogLocation();
            VisibleRegion = MapSpan.FromCenterAndRadius(
                new Position(mostRecentDogLocation.Latitude, mostRecentDogLocation.Longitude),
                Distance.FromMeters(5));

            MoveToRegionRequest.MoveToRegion(VisibleRegion);
        }
    }
}
`

@nuitsjp Could you please help me figure out the problem? I've searched endlessly and couldn't figure it out.
Thanks!

**Comment by imsagarchopra** [comment]
There is a missing public "Request" property to make it publicly visible in xaml :
Can be fixed like 
public BindableProperty Request
        {
            get { return (BindableProperty)GetValue(RequestProperty); }
            set { SetValue(RequestProperty, value); }
        }

**Comment by nuitsjp** [comment]
I'm sorry it took so long.
It is now officially supported in the new release.

- https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/releases/tag/Release-3.0.0

Please use this version from now on.
Thank you for your cooperation.
