### ISSUE TITLE
The Property 'CameraUpdate' was not found in Type 'UpdateCameraPositionBehavior'

### ISSUE THREAD

**Issue by FANMixco** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#19]
Hi, I'm developing an app with Xamarin.Forms 3.3.0.967583 and I'm facing the issue that the camera position is never updated, I have the following code:

XAML:
`            <maps:Map x:Name="map"
                      VerticalOptions="FillAndExpand">
                <maps:Map.Behaviors>
                    <bindings:BindingPinsBehavior Value="{Binding Pins}"/>
                    <bindings:MapClickedToCommandBehavior Command="{Binding MapClickedCommand}"/>
                    <bindings:UpdateCameraPositionBehavior CameraUpdate="{Binding CameraUpdate}" Duration="{Binding Duration}"></bindings:UpdateCameraPositionBehavior>
                </maps:Map.Behaviors>
            </maps:Map>
`

C# View:

`        protected override void OnAppearing()
        {
            base.OnAppearing();
            ((MapViewModel)BindingContext).Pins.Add(new Pin() { Type = PinType.Place, Label = "Boutique Hotel", Address = "Piłsudskiego 10, 90-368 Łódź, Poland", Position = new Position(51.760082d, 19.461088d), Tag = "tm_hotel" });

            ((MapViewModel)BindingContext).UpdateCameraLocation.Execute(true);
        }
`

C# ViewModel:

`
		class MapViewModel : BaseViewModel, INotifyPropertyChanged
		{
			private bool animated = false;
			private double latitude = 0;
			private double longitude = 0;

        public ObservableCollection<Pin> Pins { get; set; } = new ObservableCollection<Pin>();

        private CameraUpdate cameraUpdate = null;

        public CameraUpdate CameraUpdate
        {
            get => cameraUpdate;
            set => SetProperty(ref cameraUpdate, value);
        }

        public bool Animated
        {
            get => animated;
            set
            {
                animated = value;
                Duration = animated ? TimeSpan.FromSeconds(2) : (TimeSpan?)null;
            }
        }

        public double Latitude
        {
            get
            {
                return latitude;
            }
            set
            {
                latitude = value;
                OnPropertyChanged(nameof(Latitude));
            }
        }

        public double Longitude
        {
            get
            {
                return longitude;
            }
            set
            {
                longitude = value;
                OnPropertyChanged(nameof(Longitude));
            }
        }

        private TimeSpan? _duration;
        public TimeSpan? Duration
        {
            get => _duration;
            set => SetProperty(ref _duration, value);
        }

        public MapViewModel()
        {
            Title = "Location";
            //                      InitialCameraUpdate="51.760082, 19.461088, 15"
            Latitude = 51.760082d;
            Longitude = 19.461088d;
        }

        public Command<MapClickedEventArgs> MapClickedCommand =>
            new Command<MapClickedEventArgs>(args =>
            {
                Pins.Add(new Pin
                {
                    Label = $"Pin{Pins.Count}",
                    Position = args.Point
                });
                Latitude = Pins[Pins.Count - 1].Position.Latitude;
                Longitude = Pins[Pins.Count - 1].Position.Longitude;
                UpdateCameraLocation.Execute(true);
            });

        public Command UpdateCameraLocation => new Command(() =>
        {
            CameraUpdate =
                CameraUpdateFactory.NewCameraPosition(
                    new CameraPosition(
                        new Position(Latitude, Longitude),
                        15d // zoom
                    ));
        });

        #region INotifyPropertyChanged implementation
		#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
        public event PropertyChangedEventHandler PropertyChanged;
		#pragma warning restore CS0108 // Member hides inherited member; missing new keyword

        private new void OnPropertyChanged(string property)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
        }
        #endregion
    }
`

Do you have any idea why is not being exposed? Thanks for your support!

**Comment by Sonnenspeer** [comment]
There is missing a public CameraUpdate property in the CameraUpdatePositionBehavior class.

Something like this:
```
public CameraUpdate CameraUpdate
{
    get { return GetValue(CameraUpdateProperty); }
    set { SetValue(CameraUpdateProperty, value); }
}
```

**Comment by nuitsjp** [comment]
I'm sorry it took so long.
It is now officially supported in the new release.

- https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/releases/tag/Release-3.0.0

Please use this version from now on.
Thank you for your cooperation.
