### ISSUE TITLE
How MoveToRegion every 5000ms

### ISSUE THREAD

**Issue by BullT** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#20]
Hi,

I want refresh every 5000ms my current position on map. I can MoveToRegion one time but when I use a Timer for MoveToRegion every 5000ms nothing happens.

Can you help me, to how move map to my current position every 5000ms?

Thanks,
BullT

**Comment by Sonnenspeer** [comment]
Is a duplication of https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/600

**Comment by nuitsjp** [comment]
I have confirmed that the problem has been resolved in the link.
Also, I think this issue is about the way Xamarin is implemented, not the library.
For this reason, I'm closing this issue.
