### ISSUE TITLE
Can not move to region upon entering MapPage.

### ISSUE THREAD

**Issue by BillyMartin1964** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#23]
Can not move to region upon entering MapPage.

If I place a button on the screen and use that, it moves just fine... but if I call the method or include the code, it shows the entire map... with the map pin exactly where it is supposed to be.

 ```
 ICommand centerOnMapPinCommand;
        public ICommand CenterOnMapPinCommand =>
            centerOnMapPinCommand ??
            (centerOnMapPinCommand = new Command(async () => await ExecuteCenterOnMapPinCommand()));

        private async Task ExecuteCenterOnMapPinCommand()
        {
            if (Pins.Count < 1)
            {
                return;
            }

            var currentPosition = Pins[0].Position;

            Request.MoveToRegion(
                MapSpan.FromCenterAndRadius(
                    new Position(currentPosition.Latitude, currentPosition.Longitude),
                    Distance.FromMeters(500)),
                Animated);

        }
```

**Comment by nuitsjp** [comment]
I tried to reproduce the Issue code in PR #24 .

It correctly moved to Tokyo right after the screen transition.
The reproduced code you described does not seem to be the cause. I am unable to investigate further.

Please fork the code in the PR and create a PR for the reproduced code. If you can reproduce it, I will look into it.

However, it may not be a problem with Xamarin.Forms.GoogleMaps.Bindings.

**Comment by BillyMartin1964** [comment]
Got it to work somewhat. (the animation doesn't work when coming into the page. ... just when button clicking), but I'm not sure why it started working.

I know it would not work if I didn't have this binding, even though I never give it a value:

  `<bindings:BindingRegionBehavior Value="{Binding CurrentRegion}" />`

I'll keep you informed. Just give me a week to see if it screws up again. Thanks so much.

**Comment by nuitsjp** [comment]
I understand. I'll be waiting for you!

**Comment by BillyMartin1964** [comment]
Okay. It is some sort of binding issue. The first time I go to the map page, it shows the entire world. If I leave the map page and come back, then it shows the map properly. I am using mvvm in Xamarin Forms Prism.

![image](https://user-images.githubusercontent.com/29313458/123072650-b739fd80-d3e3-11eb-9d1b-c49198850e1b.png)


![image](https://user-images.githubusercontent.com/29313458/123072771-d20c7200-d3e3-11eb-93d1-59cf84333df3.png)

**Comment by nuitsjp** [comment]
Since you are using Prism, do you use INavigatingAware or something similar to handle the screen transitions?
Please let me know in which event you call "MoveToRegion".

**Comment by nuitsjp** [comment]
Since there has been no response, it will be closed once.
If you have any questions, please respond again and I will do my best to help.
