### ISSUE TITLE
How to use MoveToRegionRequest

### ISSUE THREAD

**Issue by straiser** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#8]
Hi. Could someone tell me how to use MoveToRegionRequest?
I tried  something like this:
`    <bindings:MoveCameraBehavior Request="{Binding MoveToRegionRequest}" />`

And in code:
` MoveToRegionRequest regionTemp = new MoveToRegionRequest();
                    regionTemp.MoveToRegion(new MapSpan(MapCenterPosition, 0, 0));
                    MoveToRegionRequest = regionTemp;`
And prop:
`     private MoveToRegionRequest moveToRegionRequest;

        public MoveToRegionRequest MoveToRegionRequest
        {
            get { return moveToRegionRequest; }
            set
            {
                moveToRegionRequest = value;
            }
        }`

But nothing happened. I want to move   visibility to some region.

**Comment by nuitsjp** [comment]
Prepared the simplest sample of MoveToRegionBehavior.
https://github.com/nuitsjp/GoogleMaps.Bindings-Sample

Please refer to the following two in the repository:

* MoveToRegionPage.xaml
* MoveToRegionPageViewModel.cs

**Comment by straiser** [comment]
Working. Thanks for help :)
