### ISSUE TITLE
Setting default map center

### ISSUE THREAD

**Issue by MaurersMake** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#9]
I'm using the googlemaps plugin and the binding plugin - love how easy they are.  However, I am confused on how to set an initial camera location other than Rome.  In my viewmodel, I create some pins from database and search criteria and then I display the pins on the map.  I then have to move the map from Rome to where I think the pins are on the map.  

Is there any way to set the initial map "center", "region", etc. to one of the pins from my list of pins so my users don't always have to pan/move from Rome?

**Comment by victorgilalejandria** [comment]
Any update on this one? It's something very needed. Any options?

**Comment by nuitsjp** [comment]
I have overlooked the proposal so far.
I would like to consider it positively.
However, it will take some time to respond.

**Comment by ryanrauch** [comment]
Any input on the best way to handle this situation?
In the mean time, have been working around it by initially hiding the visibility of the map. Creating a variable inside the viewmodel holding the desired start location, sending a MoveToRegionRequest to that location in the OnAppearing event, and then comparing desired location to the map's VisibleRegion property each time VisibleRegion is set. Once they match, can display the map, and start processing.

Would be willing to send pull request and modify code for you if you could provide guidance towards a better solution?

**Comment by nuitsjp** [comment]
Supported Release 2.2.0.
Please use UpdateRegionBehavior.

Sample:
https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/blob/master/Sample/GoogleMaps.Bindings/GoogleMaps.Bindings/Views/UpdateRegionPage.xaml#L27
